# Site settings
# ------------- General Settings -------------
title: Nijin Jose                       # Your name or company name
name: Nijin Jose
description: >-                      # Your site description
  Data Scientist and Machine Learning Engineer with 3+ years of experience in developing, deploying,
  and operationalizing machine learning models, with a strong focus on MLOps and scalable AI solutions.
  Passionate about advancing AI through research and practical applications.
  
  [Email](mailto:nijinxose@gmail.com) | [LinkedIn](https://linkedin.com/in/nijinjose) | 
  [GitHub](https://github.com/nijinjose) | [Google Scholar](https://scholar.google.com/citations?user=7e7_dq0AAAAJ)
baseurl: "/Codex-portfolio"                       # The subpath of your site
url: "https://nijinjose.github.io"                # The base hostname & protocol for your site, e.g. http://example.com. If hosted on GitHub Pages at username.github.io, set to https://username.github.io
repository: nijinjose/Codex-portfolio             # Your GitHub repository for GitHub Pages, e.g. username/username.github.io

# ------------ Profile & Social Links -------------
email: nijinxose@gmail.com
twitter_username: 
github_username:  nijinjose
linkedin_username: nijinjose
scholar_userid: 7e7_dq0AAAAJ  # Replace with actual ID

# ------------ Build Settings -------------
markdown: kramdown
theme: # al-folio needs to be installed as a gem or remote theme
remote_theme: alshedivat/al-folio # Using remote theme for easier setup

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed
  load_paths:
    - _sass
    - assets/css
    - vendor/bundle/ruby/*/gems/*/lib/assets/stylesheets
    - vendor/bundle/ruby/*/gems/*/assets/stylesheets

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-scholar # For managing publications
  - jekyll-toc # For table of contents
  - jekyll-remote-theme # Required for remote_theme

# ------------ Theme Settings (al-folio specific) -------------
# See: https://github.com/alshedivat/al-folio/blob/master/_config.yml
# for full configuration options.

# General appearance
appearance:
  theme_toggle: true # Enable light/dark mode toggle
  theme: light # Default theme: light, dark, auto

# Navigation bar settings
nav_pages:
  - {title: 'Home', url: '/'}
  - {title: 'Projects', url: '/projects/'}
  - {title: 'Publications', url: '/publications/'}
  - {title: 'CV', url: '/cv/'}
  - {title: 'Blog', url: '/blog/'}

# Footer settings
year: 2024 # Copyright year

# Publications settings
scholar:
  style: apa # Citation style, e.g., apa, mla, ieee
  locale: en

  sort_by: year # Order publications by year
  order: descending

  source: /_bibliography/papers.bib # Path to your BibTeX file
  bibliography_template: bib # Template for displaying publications

# Projects settings
# Define projects in _projects/ or use a data file like _data/projects.yml
# Example below assumes using markdown files in _projects/
# projects:
#   sort_by: date # date, importance, title
#   sort_order: descending # ascending, descending
#   # projects_page_title: Projects # Title for the projects page

# Blog settings
# blog_name: Blog # Name for the blog section
# blog_description: My thoughts and insights

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE.txt
